#' Input for Day1 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day1_input`
#' A single string containing several blocks of lines separated by blank lines. 
#' Each non-empty line contains an integer.
#' 
#' @source <https://adventofcode.com/2022/day/1>
"day1_input"


#' Input for Day2 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day2_input`
#' A single string containing one Rock Paper Scissors Strategy Guide item per line
#' \describe{
#'   \item{OpponentPlay}{Opponent play encoded as 'A' = 'Rock', 'B' = 'Paper' and 'C' = 'Scissors}
#'   \item{ResponseCode}{Reponse code with values 'X', 'Y' and 'Z'; function not specified}
#' }
#' 
#' @source <https://adventofcode.com/2022/day/2>
"day2_input"


#' Input for Day3 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day3_input`
#' A single string containing the contents of one rucksack at a time
#' Each letter represents an item type. The first half of the items is in the left and the other half in the right compartment.
#' 
#' @source <https://adventofcode.com/2022/day/3>
"day3_input"


#' Input for Day4 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day4_input`
#' A single string containing one pair of section ranges per line.
#' Section ranges are presented as a pair of integers separated by a hyphen.
#' 
#' @source <https://adventofcode.com/2022/day/4>
"day4_input"


#' Input for Day5 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day5_input`
#' A single string containing two parts separated by an empty line.
#' The first section is a depiction of the initial stack configuration.
#' The second section is a list of moves to perform, one per line.
#' 
#' @source <https://adventofcode.com/2022/day/5>
"day5_input"


#' Input for Day6 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day6_input`
#' A single string of seemingly random characters representing a communication signal.
#' 
#' @source <https://adventofcode.com/2022/day/6>
"day6_input"


#' Input for Day7 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day7_input`
#' A single string of console output generated by browsing a file system.
#' Each command starts with a $ on a new line. 
#' Lines not starting with a $ are command outputs.
#' 
#' @source <https://adventofcode.com/2022/day/7>
"day7_input"


#' Input for Day8 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day8_input`
#' A single string containing a square grid of tree heights.
#' 
#' @source <https://adventofcode.com/2022/day/8>
"day8_input"


#' Input for Day9 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day9_input`
#' A single string containing one move of the form 'direction distance' per line, where U, D, L, R encode the directions
#' 
#' @source <https://adventofcode.com/2022/day/9>
"day9_input"


#' Input for Day10 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day10_input`
#' A single string containing one CPU instruction per line
#' 
#' @source <https://adventofcode.com/2022/day/10>
"day10_input"


#' Input for Day11 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day11_input`
#' A single string containing monkey descriptions separated by empty lines
#' \describe{
#'   \item{Starting items}{A list of integers indicating your initial worry for each items the monkey holds}
#'   \item{Operation}{A formula describing how your worry about an item changes when the monkey inspects it}
#'   \item{Test}{An if-else expression describing to which monkey the item will be passed based on your worry about the item}
#' }
#' 
#' @source <https://adventofcode.com/2022/day/11>
"day11_input"


#' Input for Day12 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day12_input`
#' A single string containing a topographic map. Each character represents a height level from 'a' = 0 to 'z' = 25. Moreover, the start point is 'S' at level 0 and the end point is 'E' at level 25. The distance between adjacent characters is 1.
#' 
#' @source <https://adventofcode.com/2022/day/12>
"day12_input"


#' Input for Day13 of Advent of Code 2022 for Max Doerner
#'
#' @format ## `day13_input`
#' A single string containing pairs of packets separated by an empty line. Each non-empty line is a packet, which is a comma-separated list of other packets and integers enclosed in square brackets
#' 
#' @source <https://adventofcode.com/2022/day/13>
"day13_input"