

#' Encode Point
#'
#' @param point A numeric vector
#'
#' @return A character vector representing the point
encode_point <- function(point) {
  paste(point, collapse = "__")
}
modules::export("encode_point")


#' Decode Point
#'
#' @param point_text A character vector representing a point as generated by `encode_point`
#'
#' @return A double vector representing the point
#' @importFrom magrittr %>%
decode_point <- function(point_text) {
  point_text %>%
    stringr::str_split(pattern = "__") %>%
    unlist() %>% 
    readr::parse_double()
}
modules::export("decode_point")

